repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        types: [nix]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

      - id: pytest
        name: pytest
        entry: pytest tests/ -q
        language: system
        pass_filenames: false
        always_run: true
