# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  name,
  config,
  lib,
  modulesPath,
  ...
}: {
  boot.loader.efi.canTouchEfiVariables = true;
  # Use the GRUB 2 boot loader.
  boot.loader.grub = {
    enable = true;
    useOSProber = true;
    efiSupport = true;
    device = "nodev";
    configurationLimit = 3;
  };
  boot.zfs.extraPools = ["zpool"];
  boot.zfs.devNodes = "/dev/disk/by-uuid/15679710222853114018";
  boot.zfs.forceImportRoot = false;
  # Cap the ZFS ARC well below half of physical RAM (~40 GiB). The default lets
  # it grow to nearly all RAM, starving applications and causing system-wide
  # sluggishness.
  #
  # 16 rather than 20 GiB, from measurement rather than taste. Ghost-list hits --
  # the cache's own record of what it would have served had it been larger -- ran
  # at 0.27% of real hits, so the working set fits with room to spare and the top
  # of the old ceiling was never worth anything. What that headroom did buy was a
  # peak that left under a gigabyte free before a build had even begun ramping,
  # which is the state a sudden allocation cannot be absorbed from.
  #
  # Not lower: metadata alone accounts for ~8 GiB here and serves seven of every
  # eight hits, a store of many small files being mostly an exercise in dnode and
  # dbuf lookups. A cap that squeezes metadata would cost far more than one that
  # squeezes cached file data.
  boot.kernelParams = ["zfs.zfs_arc_max=${toString (16 * 1024 * 1024 * 1024)}"];

  # Compressed cache in front of the swap partition. A build that outgrows RAM
  # gets its cold pages compressed in place instead of faulting against the SATA
  # SSD, which is what the userspace OOM killer actually measures: it kills on
  # stall time, not on free memory, so cheaper paging is what keeps a build alive.
  # The pool competes with the ARC for the same RAM, so it is kept well under the
  # module default of 25% -- 15% of 40 GiB holds roughly three times that in
  # compressed anonymous pages. The shrinker is what lets the pool hand memory
  # back rather than becoming a second cache the ARC has to fight.
  boot.zswap = {
    enable = true;
    maxPoolPercent = 15;
    shrinkerEnabled = true;
  };
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  networking.hostName = name;
  networking.hostId = "cb8907f7";
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "zpool/root";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  fileSystems."/nix" = {
    device = "zpool/nix";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  fileSystems."/var" = {
    device = "zpool/var";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  fileSystems."/home" = {
    device = "zpool/home";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  # LLM service storage (models, wiki corpus, Open WebUI state).
  # Dataset is created manually with a 200G quota — see docs/local-llm-service.md D7.
  fileSystems."/var/lib/llm" = {
    device = "zpool/llm";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  # Open WebUI state. The upstream unit hardcodes StateDirectory="open-webui"
  # and runs with DynamicUser, so its data lands in /var/lib/private/open-webui
  # with systemd owning the permissions — a stateDir pointed under /var/lib/llm
  # would need a chown to a UID that only exists at runtime. Mounting a child of
  # zpool/llm here keeps the state inside the 200G quota (ZFS quotas bound a
  # dataset and its descendants) without fighting the dynamic UID.
  # Dataset is created manually — see scripts/deploy-llm-phase2.sh.
  fileSystems."/var/lib/private/open-webui" = {
    device = "zpool/llm/open-webui";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  # Paperless document archive. The SQLite database, the OCR'd media tree and
  # the nightly export all live under this one mountpoint, so the quota has to
  # cover roughly twice the document volume — ZFS quotas bound a dataset and
  # its descendants. Dataset is created manually with a 100G quota, and carries
  # com.sun:auto-snapshot=true — see docs/paperless.md.
  fileSystems."/var/lib/paperless" = {
    device = "zpool/paperless";
    fsType = "zfs";
    options = ["zfsutil"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/19D5-7538";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  # Swap is split across two disks by priority rather than striped across them.
  # The pool lives on the same device as the original swap partition, so under
  # memory pressure swap writes and pool reads queued behind each other on one
  # SATA queue -- which is part of why a stall became total rather than merely
  # slow. Equal priorities would round-robin and put writes back on that device
  # on every swap, so the disk without the pool is given a higher priority and
  # the original is left as overflow.
  swapDevices = [
    # Preferred. Also the only drive here that caches its mapping table in
    # onboard DRAM, which matters for swap specifically: 4K random access with
    # no locality is the worst case for a controller that has to fetch that
    # table from flash first.
    {
      device = "/dev/disk/by-uuid/2180e14b-1c1e-49ba-99e7-a404f6be78ee";
      priority = 100;
      # fstrim covers filesystems, not swap, so a swap partition is never
      # trimmed unless it is asked for here.
      discardPolicy = "once";
    }
    # Overflow only, on the pool's disk. Deliberately left without an explicit
    # priority: the kernel auto-assigns a negative one, which is already below
    # the entry above, and naming a number here would rewrite this unit and make
    # activation swapoff a device with several GiB live in it -- a bulk fault of
    # everything it holds back into RAM, which is the one allocation pattern
    # this whole arrangement exists to avoid.
    {device = "/dev/disk/by-uuid/7a266111-38df-4c46-9303-d10f52ae4f95";}
  ];

  # Additional drives - nofail so boot continues if not present
  fileSystems."/run/media/vringar/Programme" = {
    device = "/dev/disk/by-uuid/6E50E22D394B927D";
    fsType = "ntfs3";
    options = ["nofail" "x-systemd.device-timeout=5" "uid=1000" "gid=100"];
  };

  fileSystems."/run/media/vringar/Daten" = {
    device = "/dev/disk/by-uuid/0A94B9F1635778A9";
    fsType = "ntfs3";
    options = ["nofail" "x-systemd.device-timeout=5" "uid=1000" "gid=100"];
  };

  fileSystems."/run/media/vringar/Backup" = {
    device = "/dev/disk/by-uuid/02e400c2-1bdd-4d46-a0dd-044d6b4f3af4";
    fsType = "ext4";
    options = ["nofail" "x-systemd.device-timeout=5"];
  };

  fileSystems."/run/media/vringar/SourceCode" = {
    device = "/dev/disk/by-uuid/ea4e895b-d179-40d9-afac-2389a6645dff";
    fsType = "ext4";
    options = ["nofail" "x-systemd.device-timeout=5"];
  };

  fileSystems."/run/media/vringar/WindowsNew" = {
    device = "/dev/disk/by-uuid/20DDDC7E711F2C91";
    fsType = "ntfs3";
    options = ["nofail" "x-systemd.device-timeout=5" "uid=1000" "gid=100"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Enable QEMU aarch64 emulation for building Pi images
  boot.binfmt.emulatedSystems = ["aarch64-linux"];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
